### add a new player
POST localhost:8080/players HTTP/1.1
Content-Type: application/json

{
  "name": "Mario",
  "lastname": "Rossi"
}

### start new game
POST localhost:8080/bowling/game HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "playerId": 1
}

### primo frame
POST localhost:8080/bowling/games/1/frames/ HTTP/1.1
Content-Type: application/json

{
  "firstShot": 1,
  "secondShot": 4
}

### secondo frame
POST localhost:8080/bowling/games/1/frames/ HTTP/1.1
Content-Type: application/json

{
  "firstShot": 4,
  "secondShot": 5
}

### terzo frame
POST localhost:8080/bowling/games/1/frames/ HTTP/1.1
Content-Type: application/json

{
  "firstShot": 6,
  "secondShot": 4
}

### quarto frame
POST localhost:8080/bowling/games/1/frames/ HTTP/1.1
Content-Type: application/json

{
  "firstShot": 5,
  "secondShot": 5
}

### quinto frame
POST localhost:8080/bowling/games/1/frames/ HTTP/1.1
Content-Type: application/json

{
  "firstShot": 10
}

### sesto frame
POST localhost:8080/bowling/games/1/frames/ HTTP/1.1
Content-Type: application/json

{
  "firstShot": 0,
  "secondShot": 1
}

### settimo frame
POST localhost:8080/bowling/games/1/frames/ HTTP/1.1
Content-Type: application/json

{
  "firstShot": 7,
  "secondShot": 3
}

### ottavo frame
POST localhost:8080/bowling/games/1/frames/ HTTP/1.1
Content-Type: application/json

{
  "firstShot": 6,
  "secondShot": 4
}

### nono frame
POST localhost:8080/bowling/games/1/frames/ HTTP/1.1
Content-Type: application/json

{
  "firstShot": 10
}

### decimo frame
POST localhost:8080/bowling/games/1/frames/ HTTP/1.1
Content-Type: application/json

{
  "firstShot": 2,
  "secondShot": 8,
  "thirdShot": 6
}

### calcolo score parziale
GET localhost:8080/bowling/game/1/score
